[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26" # we need a version that supports blobhash()

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
