[package]
name = "blob"
type = "bin"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
# bignum = {tag = "v0.4.0", git = "https://github.com/noir-lang/noir-bignum" }
bignum = {path = "../../../noir-bignum"}